FROM golang:1.19-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY *.go ./

RUN go test

RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

RUN golangci-lint run

RUN go install golang.org/x/vuln/cmd/govulncheck@latest

RUN govulncheck -v ./

RUN go build -o /unit-test

FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /unit-test /unit-test

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT [ "/unit-test" ]
