FROM golang:1.17-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY *.go ./

RUN go test

RUN go build -o /unit-test

FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /unit-test /unit-test

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT [ "/unit-test" ]
