# version: 2.1
# jobs:
#   run_tests:
#     docker:
#       - image: cimg/go:1.20.2
#     steps:
#       - run: echo "Say hello to GoLang Project!"
#       - run: go version
#       - checkout
#       - run:
#           name: Install go mods
#           command: |
#             go mod download
#             go version
#       - run:
#           name: Run unit test
#           command: |
#             go test

# workflows:
#   first_circle_ci:
#     jobs:
#       - run_tests

version: 2.1
jobs:
  test_project:
    docker:
      - image: cimg/go:1.20.2
    steps:
      - run: echo "Starting project test"
      - run: go version
      - checkout
      - run:
          name: Install go mods
          command: |
            go mod download
      - run:
          name: Run unit test
          command: |
            go test

  build_docker_image:
    docker:
      - image: cimg/base:2022.03
        # auth:
        #   username: pranay999000
        #   password: Confidential@02
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - run:
          command: |
            docker build -t pranay999000/unit-test:$CIRCLE_BRANCH -f Dockerfile.multistage .
      - run:
          command: |
            docker login --username pranay999000 --password Confidential@02
            docker push pranay999000/unit-test:$CIRCLE_BRANCH

workflows:
  docker_image:
    jobs:
      - test_project
      - build_docker_image
