apiVersion: v1
kind: Service
metadata:
  name: {{ include "unit-test-chart.fullname" . }}
  labels: {{- include "unit-test-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector: {{- include "unit-test-chart.selectorLabels" . | nindent 4 }}
